# Generated by Django 4.2.2 on 2023-07-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0005_alter_author_author_description'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_name',
            new_name='Book',
        ),
    ]