# Generated by Django 4.2.1 on 2023-06-21 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0005_alter_author_author_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Book title')),
                ('cover_image', models.ImageField(blank=True, upload_to='book_images/', verbose_name='Book image')),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Book price')),
                ('publication_year', models.DateField(verbose_name='Publication year')),
                ('pages', models.PositiveIntegerField(verbose_name='Number of pages')),
                ('binding', models.CharField(choices=[('Soft', 'soft'), ('Solid', 'solid')], max_length=255, verbose_name='Tipe of binding')),
                ('format', models.CharField(choices=[('A3', '100*100'), ('A4', '200*200')], max_length=255, verbose_name='Book Format')),
                ('isbn', models.CharField(max_length=255, verbose_name='ISBN')),
                ('weight', models.PositiveIntegerField(verbose_name='Weight')),
                ('age_limit', models.CharField(max_length=255, verbose_name='Age limit')),
                ('quantity_available', models.PositiveIntegerField(verbose_name='Count')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activity')),
                ('rating', models.CharField(choices=[('A3', '100*100'), ('A4', '200*200')], max_length=255, verbose_name='Rating')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date of adding')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date of changing')),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directories.author', verbose_name='Book author')),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directories.genres', verbose_name='Book genre')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directories.publishing', verbose_name='Publisher')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directories.series', verbose_name='Book series')),
            ],
        ),
    ]