# Generated by Django 4.2.1 on 2023-06-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='Author name')),
                ('author_description', models.TextField(blank=True, null=True, verbose_name='Author description')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50, verbose_name='Genre')),
                ('genre_description', models.TextField(blank=True, null=True, verbose_name='Genre description')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Publication_name', models.CharField(max_length=50, verbose_name='Publishion name')),
                ('publishion_description', models.TextField(blank=True, null=True, verbose_name='Publishion description')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=100, verbose_name='Series')),
                ('series_description', models.TextField(blank=True, null=True, verbose_name="Count book's series")),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50, verbose_name='Book name')),
                ('book_image', models.ImageField(blank=True, default='/book/book-default.jpg', upload_to='book/%Y/%m/%d/')),
                ('book_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('year_publishing', models.DateField(max_length=50, verbose_name='Year publishing book')),
                ('page', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('binding', models.CharField(choices=[('Solid', 'solid'), ('Soft', 'soft'), ('Absent', 'absent')], max_length=6, verbose_name='Binding book')),
                ('format_book', models.CharField(choices=[('Super small', '84x108/64'), ('Small', '75x90/32'), ('Standart', '60x90/16'), ('Bigger', '70x108/16'), ('Big', '60x90/8'), ('Super big', '84x108/8')], max_length=12, verbose_name='Book format')),
                ('ISBN', models.CharField(max_length=25, verbose_name='ISBN')),
                ('weight', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Book weight(gramme)')),
                ('age_restrictions', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Age restrictions')),
                ('counter_book', models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='Count of books available')),
                ('active', models.CharField(choices=[('Y', 'active'), ('N', 'inactive')], max_length=4, verbose_name='Book active')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Rating')),
                ('Publication_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dirictories.publication', verbose_name='Publication name')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dirictories.author', verbose_name='author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dirictories.genre', verbose_name='genre')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dirictories.series', verbose_name='series')),
            ],
        ),
    ]
