# Generated by Django 4.2.1 on 2023-05-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Genre name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Genre description')),
            ],
        ),
    ]