# Generated by Django 4.2.1 on 2023-05-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Author name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Basic information')),
            ],
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Genre name'),
        ),
    ]