# Generated by Django 4.2.1 on 2023-07-6 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0002_author_alter_genres_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Publishing name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Publishing information')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Series count')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Series information')),
            ],
        ),
    ]