# Generated by Django 4.2.2 on 2023-07-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0003_publishing_series'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='description',
            new_name='author_description',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='genres',
            old_name='description',
            new_name='genre_description',
        ),
        migrations.RenameField(
            model_name='genres',
            old_name='name',
            new_name='genre_name',
        ),
        migrations.RenameField(
            model_name='publishing',
            old_name='description',
            new_name='publishing_description',
        ),
        migrations.RenameField(
            model_name='publishing',
            old_name='name',
            new_name='publishing_name',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='description',
            new_name='series_description',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='name',
            new_name='series_name',
        ),
    ]