# Generated by Django 4.2.2 on 2023-07-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0004_rename_description_author_author_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_description',
            field=models.TextField(blank=True, null=True, verbose_name='Author information'),
        ),
    ]