# Generated by Django 4.2.1 on 2023-07-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_adress',
            field=models.TextField(blank=True, verbose_name='Delivery adress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('In process', 'In process'), ('Ready', 'Ready')], 
            max_length=255, verbose_name='Order status'),
        ),
    ]