# Generated by Django 4.2.1 on 2023-07-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_order_delivery_adress_alter_order_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_adress',
        ),
    ]