# Generated by Django 4.2.1 on 2023-07-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_order_delivery_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(blank=True, to='cart.bookincart', verbose_name='Books in cart'),
        ),
    ]