# Generated by Django 4.2.1 on 2023-05-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0002_publichollidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHollydays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hollyday name')),
                ('holliday_date', models.DateField(verbose_name='Hollyday name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Hollyday description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created datetimed')),
                ('update', models.DateField(auto_now=True, verbose_name='Updated datetime')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Region name')),
            ],
        ),
        migrations.DeleteModel(
            name='PublicHollidays',
        ),
    ]
